- name: Install java 8 preresequesits
  apt: name=python-software-properties

- name: Add Java 8 repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Agree to oracle license
  debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

- name: Install Java 8
  apt: name=oracle-java8-installer force=yes

#- name: set JAVA_HOME environment variable
#  lineinfile: path=/home/ubuntu/.profile line='export JAVA_HOME=/usr/lib/jvm/java-8-oracle' insertafter=EOF

#- name: set JAVA PATH environment variable
#  lineinfile: path=/home/ubuntu/.profile line='export PATH=$PATH:$JAVA_HOME' insertafter=EOF
