---
- hosts: localmachine
  tasks:
    - name: check process
      shell: "ps -ef | grep tomcat | grep -v grep | wc -l"
      register: tomcat_process

    - name: stop tomcat
      become: yes
      shell: initctl stop tomcat
      when: "tomcat_process.stdout != 0"
