- name: Tomcat8 Installation By using zip file
  get_url:
    url: http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.11/bin/apache-tomcat-8.5.11.tar.gz
    dest: /home/ubuntu/mahesh/tomcat
    owner: ubuntu
    group: ubuntu
    

- name: Un-Archive zip file
  unarchive:
    src: /home/ubuntu/mahesh/tomcat/apache-tomcat-8.5.11.tar.gz
    dest: /home/ubuntu/mahesh/tomcat/
    copy: no

- name: change permissions file
  file: path=/home/ubuntu/mahesh/tomcat/apache-tomcat-8.5.11 owner=ubuntu group=ubuntu recurse=yes
    

- name: service tomcat start
  command: chdir=/home/ubuntu/mahesh/tomcat/apache-tomcat-8.5.11/bin ./startup.sh
